<?xml version="1.0" encoding="utf-8"?><Database Name="LTUDQL1" Class="LTUDQL1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI\SQLEXPRESS;Initial Catalog=LTUDQL1;Integrated Security=True" SettingsObjectName="DoAnCuoiKy.Properties.Settings" SettingsPropertyName="LTUDQL1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[USER]" Member="USERs">
    <Type Name="USER">
      <Column Name="f_HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="f_MaSo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="f_Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="f_GioiTinh" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="f_NgaySinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="f_Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="f_TenDangNhap" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="f_MatKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="f_IDPhanQuyen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.KyThi" Member="KyThis">
    <Type Name="KyThi">
      <Column Name="MaKT" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ngay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaDT" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaHV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.KetQua" Member="KetQuas">
    <Type Name="KetQua">
      <Column Name="MaHV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaKT" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Diem" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BoDe" Member="BoDes">
    <Type Name="BoDe">
      <Column Name="MaBD" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDK" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CauHoi" Member="CauHois">
    <Type Name="CauHoi">
      <Column Name="MaCH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CapHoc" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MonHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DapAnA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DapAnB" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DapAnC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DapAnD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DapAnDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeThi" Member="DeThis">
    <Type Name="DeThi">
      <Column Name="MaDT" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDK" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaBD" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>